# Generated by Django 2.0.3 on 2018-04-02 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em atendimento', 'Em atendimento'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('solicitante', models.ManyToManyField(blank=True, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FCSolutions.Chamado'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='funcionario',
            field=models.ManyToManyField(blank=True, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitanteAtendimento',
            field=models.ManyToManyField(blank=True, related_name='solicitanteAtendimento', to=settings.AUTH_USER_MODEL),
        ),
    ]
