# Generated by Django 2.0.3 on 2018-04-02 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FCSolutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='dataAbertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FCSolutions.Chamado'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='funcionario',
            field=models.ManyToManyField(blank=True, related_name='Atendente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='solicitanteAtendimento',
            field=models.ManyToManyField(blank=True, related_name='Solicitou', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.ManyToManyField(blank=True, related_name='Solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
